"""Shared logic for constructing AiiDA-QuantumESPRESSO builders with
resource-adaptive metadata.options, so every workflow module applies the same
electron-counting / resource-estimation / local-vs-remote logic instead of
duplicating it.
"""
from __future__ import annotations

from ase import Atoms

from harness_dft.environment import get_local_resources
from harness_dft.estimate import estimate_job, choose_resources
from harness_dft.structures import count_valence_electrons, is_likely_metal


def get_electronic_type(atoms: Atoms):
    from aiida_quantumespresso.common.types import ElectronicType
    return ElectronicType.METAL if is_likely_metal(atoms) else ElectronicType.INSULATOR


def apply_ecutwfc(base_builder, ecutwfc_ry: float):
    """Override the plane-wave cutoff on a PwBaseWorkChain-level builder's
    nested `.pw.parameters`, without touching k-points (needed for the
    'bands' sub-step of PwBandsWorkChain, whose k-path is auto-generated by
    seekpath and must not be overwritten with an explicit mesh).

    ecutrho is scaled to preserve whatever dual ratio the protocol/pseudo
    family had already set, since the correct dual is pseudopotential-type
    dependent (norm-conserving vs. ultrasoft/PAW) and shouldn't be guessed.
    """
    from aiida import orm

    params = base_builder.pw.parameters.get_dict()
    system = params.setdefault("SYSTEM", {})
    current_ecutwfc = system.get("ecutwfc", ecutwfc_ry)
    current_ecutrho = system.get("ecutrho", ecutwfc_ry * 8)
    dual = current_ecutrho / current_ecutwfc if current_ecutwfc else 8.0
    system["ecutwfc"] = ecutwfc_ry
    system["ecutrho"] = ecutwfc_ry * dual
    base_builder.pw.parameters = orm.Dict(dict=params)


def apply_calculation_settings(base_builder, kpoints_mesh: tuple[int, int, int], ecutwfc_ry: float):
    """Force an explicit k-point mesh and plane-wave cutoff onto a
    PwBaseWorkChain-level builder (i.e. one with top-level `.kpoints` and
    `.pw.parameters` ports: `builder` itself for PwBaseWorkChain, or
    `builder.base/base_final_scf/scf/nscf` for the workchains that wrap it).

    Without this, `get_builder_from_protocol()`'s auto-picked
    `kpoints_distance` and pseudopotential-recommended ecutwfc silently win,
    which makes k-point/cutoff convergence sweeps meaningless -- the actual
    calculation never sees the values callers think they're testing.
    """
    from aiida import orm

    kpoints = orm.KpointsData()
    kpoints.set_kpoints_mesh(kpoints_mesh)
    base_builder.kpoints = kpoints
    base_builder.pop("kpoints_distance", None)
    apply_ecutwfc(base_builder, ecutwfc_ry)


def apply_resource_plan(pw_builder, atoms: Atoms, pseudo_family_label: str,
                         ecutwfc_ry: float, kpoints_mesh: tuple[int, int, int],
                         allow_remote: bool = False, allow_gpu: bool = False,
                         local_atom_ceiling: int = 40, cpu_batch_size: int = 8):
    """Mutate a PwCalculation builder namespace (e.g. `builder.pw` for
    PwBaseWorkChain, or `builder.base.pw` for PwRelaxWorkChain) in place with
    an estimated mpiprocs/npool/walltime, and return the ExecutionPlan used
    so callers can log/inspect the decision (e.g. to pick a remote or GPU
    code -- this function only sets resource options, it never swaps
    `pw_builder.code` itself, since it doesn't know what codes are registered).
    """
    from aiida import orm

    pseudo_family = orm.load_group(pseudo_family_label)
    n_electrons = count_valence_electrons(atoms, pseudo_family)
    n_kpoints = kpoints_mesh[0] * kpoints_mesh[1] * kpoints_mesh[2]

    job = estimate_job(
        n_atoms=len(atoms),
        n_electrons=n_electrons,
        cell_volume_ang3=atoms.get_volume(),
        ecutwfc_ry=ecutwfc_ry,
        n_kpoints=max(1, n_kpoints),
        is_metal=is_likely_metal(atoms),
    )
    plan = choose_resources(
        job, get_local_resources(), allow_remote=allow_remote, allow_gpu=allow_gpu,
        local_atom_ceiling=local_atom_ceiling, cpu_batch_size=cpu_batch_size,
    )

    pw_builder.metadata.options.resources = {
        "num_machines": 1,
        "num_mpiprocs_per_machine": plan.mpiprocs,
    }
    pw_builder.metadata.options.max_wallclock_seconds = plan.walltime_seconds

    # Not every QE CalcJob plugin exposes a `parallelization` port (pw.x does,
    # ph.x doesn't); a builder namespace silently accepts unknown attributes
    # (validated only at submit time), so check `_valid_fields` explicitly.
    if plan.npool > 1 and "parallelization" in pw_builder._valid_fields:
        pw_builder.parallelization = orm.Dict(dict={"npool": plan.npool})

    return plan
